name: Auto Update

on:
  schedule:
    - cron: '0 */6 * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update timestamp
        run: |
          echo "$(date)" > last-update.txt

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "Auto update" || exit 0
          git push
